name: SMAP
channels:
  - conda-forge
  - travis
  - defaults
dependencies:
  - pandas
  - numpy
  - matplotlib
  - dask
  - bottleneck
  - pytest-shutil
  - geopandas
  - rasterio
  - xarray
  - pyproj
  - gdal
  - cartopy
  - odc-stac
  - planetary-computer
  - rioxarray
  - pystac-client
  - fiona
  - shapely
  - rich
  - scikit-learn
  - scipy
  - netcdf4
  - pygeogrids
  - tqdm
  - sparse
  - seaborn
